# 默认端口号
server:
  port: 40001

# 激活指定的profile
spring:
  profiles:
    active: '@profileActive@'

---
spring:
  application:
    name: wear-store
  jackson:
    date-format: yyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  banner:
    charset: UTF-8
    location: classpath:config/banner.txt

wear-store:
  # 是否启用ansi控制台输出有颜色的字体，dev环境建议开启，服务器环境设置为false
  enable-ansi: false

---
# logback.xml中有详细的日志配置
logging:
  config: classpath:config/logback.xml
  #  方便Spring Boot Admin页面上实时查看日志
  file:
    path: logs/ws.log

# Filter 配置
wear-store:
  # 过滤器配置
  filter:
    # 请求路径Filter配置
    request-path:
      enabled: true
      include-paths: /**
      # 排除路径，多行字符串配置
      exclude-paths: |
        /applications/**,/actuator/**,/instances/**,/logfile,/sba-settings.js,/assets/img/favicon.png,
        /swagger-ui.html,/swagger-resources/**,/webjars/springfox-swagger-ui/**,/v2/api-docs,
        /druid/**,/favicon.ico


# 自定义项目信息，Spring Boot Admin展示使用
info:
  project-groupId: '@project.groupId@'
  project-artifactId: '@project.artifactId@'
  project-name: '@project.name@'
  project-finalName: '@project.build.finalName@'
  project-author: ${swagger.contact.name}
  project-description: '@project.description@'
  project-sourceEncoding: '@project.build.sourceEncoding@'
  project-spring-boot-version: '@spring-boot.version@'
  project-mybatis-plus-version: '@mybatis-plus-boot-starter.version@'
  project-version: '@project.version@'