# 默认端口号
server:
  port: 40001

#激活指定的profile
spring:
  profiles:
    active: dev

# logback.xml中有详细的日志配置
logging:
  config: classpath:config/logback.xml
  #  方便Spring Boot Admin页面上实时查看日志
  file:
    path: logs/ws.log
